---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ nginx.service_dir }}"
    - "{{ nginx.service_dir }}/exporter"
    - "{{ nginx.certs_dir }}"
    - "{{ nginx.conf_dir }}"
    - "{{ nginx.services_dir }}"
    - "{{ nginx.services_dir }}/nginx"
    - "{{ nginx.templates_dir }}"

- name: Install packages
  apt:
    name:
      - python-passlib

- name: Upload service file
  copy:
    src: nginx.service
    dest: "{{ nginx.services_dir }}/nginx/run"
    mode: "a+x"

- name: Upload docker file
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - src: Dockerfile
      dest: "{{ nginx.service_dir }}/Dockerfile"
  notify: restart nginx

- name: Assemble docker-compose file
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: docker-compose.yml
      dest: "{{ nginx.service_dir }}/docker-compose.yml"
    - src: nginx.conf
      dest: "{{ nginx.service_dir }}/nginx.conf"
  notify: restart nginx

- name: Assemble logrotate config
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/nginx
